INSERT INTO products (product_id, name, price, category) VALUES (1, 'Laptop Pro X', 1200.99, 'Electrónica');
INSERT INTO products (product_id, name, price, category) VALUES (2, 'Smartphone Ultra', 899.50, 'Electrónica');
INSERT INTO products (product_id, name, price, category) VALUES (3, 'Auriculares Bluetooth', 150.75, 'Accesorios');
INSERT INTO products (product_id, name, price, category) VALUES (4, 'Teclado Mecánico', 99.99, 'Accesorios');
INSERT INTO products (product_id, name, price, category) VALUES (5, 'Monitor 4K', 750.00, 'Electrónica');
INSERT INTO products (product_id, name, price, category) VALUES (6, 'Cámara Digital', 650.20, 'Fotografía');
INSERT INTO products (product_id, name, price, category) VALUES (7, 'Mochila Antirrobo', 49.99, 'Moda');
INSERT INTO products (product_id, name, price, category) VALUES (8, 'Reloj Inteligente', 200.30, 'Accesorios');
INSERT INTO products (product_id, name, price, category) VALUES (9, 'Cargador Rápido', 25.50, 'Accesorios');
INSERT INTO products (product_id, name, price, category) VALUES (10, 'Tablet Pro', 550.80, 'Electrónica');
INSERT INTO products (product_id, name, price, category) VALUES (11, 'Router Wifi 6', 120.00, 'Electrónica');
INSERT INTO products (product_id, name, price, category) VALUES (12, 'Silla Gamer', 320.50, 'Muebles');
INSERT INTO products (product_id, name, price, category) VALUES (13, 'Micrófono Profesional', 180.00, 'Accesorios');
INSERT INTO products (product_id, name, price, category) VALUES (14, 'SSD NVMe 1TB', 135.99, 'Almacenamiento');
INSERT INTO products (product_id, name, price, category) VALUES (15, 'Impresora Multifunción', 210.89, 'Oficina');
INSERT INTO products (product_id, name, price, category) VALUES (16, 'Lámpara LED', 29.99, 'Hogar');
INSERT INTO products (product_id, name, price, category) VALUES (17, 'Mouse Ergonómico', 49.99, 'Accesorios');
INSERT INTO products (product_id, name, price, category) VALUES (18, 'Estación de Carga', 75.00, 'Accesorios');
INSERT INTO products (product_id, name, price, category) VALUES (19, 'Disco Externo 2TB', 140.50, 'Almacenamiento');
INSERT INTO products (product_id, name, price, category) VALUES (20, 'Mando Inalámbrico', 69.99, 'Accesorios');